language: php

services:
  # - memcached
  # - mongodb
    - mysql
  # - rabbitmq
 # - redis-server

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  # beanstalkd
  - sudo apt-get install -qq --force-yes beanstalkd
  - sudo beanstalkd -d -l 127.0.0.1 -p 11300

  # mysql
  - mysql -e 'CREATE DATABASE database_name;'
  - mysql database_name < config/schema-mysql.sql

  # extensions
 # - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 # - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  #- echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  - composer self-update
  - composer install
  - pear install --alldeps PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=psr2 src/
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

#after_success:
 # - "composer require --dev satooshi/php-coveralls:dev-master && php vendor/bin/coveralls -v"
